name: Wheels

on:
  workflow_dispatch:

env:
  REPO_DIR: pillow-avif-plugin
  BUILD_DEPENDS: ""
  TEST_DEPENDS: "pytest pillow"
  MACOSX_DEPLOYMENT_TARGET: "10.10"
  WHEEL_SDIR: wheelhouse
  CONFIG_PATH: pillow-avif-plugin/wheelbuild/config.sh
  LIBAVIF_VERSION: 88d3dccda111f6ccbcccd925179f67e7d6fdf4ff

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        architecture: ["x64"]
        include:
          - architecture: "x64"
            platform-vcvars: "x86_amd64"
            platform-msbuild: "x64"
    timeout-minutes: 300

    name: ${{ matrix.python-version }} windows ${{ matrix.architecture }}

    steps:
    - name: Checkout pillow-avif-plugin
      uses: actions/checkout@v3

    - name: Checkout cached dependencies
      uses: actions/checkout@v3
      with:
        repository: python-pillow/pillow-depends
        path: winbuild\depends

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key:
          ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/.github/workflows/test-windows.yml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
          ${{ runner.os }}-${{ matrix.python-version }}-

    # sets env: pythonLocation
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: python -m pip install wheel pytest pytest-cov mock
      run: python -m pip install wheel pytest pytest-cov mock

    - name: Install dependencies
      id: install
      run: |
        7z x winbuild\depends\nasm-2.16.01-win64.zip "-o$env:RUNNER_WORKSPACE\"
        echo "$env:RUNNER_WORKSPACE\nasm-2.16.01" >> $env:GITHUB_PATH

        python -m pip install meson

        # make cache key depend on VS version
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" `
          | find """catalog_buildVersion""" `
          | ForEach-Object { $a = $_.split(" ")[1]; echo "vs=$a" >> $env:GITHUB_OUTPUT }
      shell: pwsh

    - name: Cache build
      id: build-cache
      uses: actions/cache@v3
      with:
        path: winbuild\build
        key:
          ${{ hashFiles('winbuild\build_prepare.py') }}-${{ hashFiles('.github\workflows\test-windows.yml') }}-${{ env.pythonLocation }}-${{ steps.install.outputs.vs }}

    - name: Prepare build
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: |
        & python.exe winbuild\build_prepare.py -v
      shell: pwsh

    - name: Build dependencies / libjpeg-turbo
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: "& winbuild\\build\\build_dep_libjpeg.cmd"

    - name: Build dependencies / zlib
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: "& winbuild\\build\\build_dep_zlib.cmd"

    - name: Build dependencies / libpng
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: "& winbuild\\build\\build_dep_libpng.cmd"

    - name: Build dependencies / meson (python 2.7)
      if: steps.build-cache.outputs.cache-hit != 'true' && matrix.python-version == '2.7'
      run: "& winbuild\\build\\install_meson.cmd"

    - name: Build dependencies / meson (python 3.x)
      if: steps.build-cache.outputs.cache-hit != 'true' && matrix.python-version != '2.7'
      run: python -m pip install meson
      shell: cmd

    - name: Build dependencies / rav1e
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: "& winbuild\\build\\build_dep_rav1e.cmd"

    - name: Build dependencies / libavif
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: "& winbuild\\build\\build_dep_libavif.cmd"

    # trim ~150MB x 9
    - name: Optimize build cache
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: rmdir /S /Q winbuild\build\src
      shell: cmd

    - name: Install dependencies / Pillow
      run: |
        cmd /c "winbuild\build\build_env.cmd && $env:pythonLocation\python.exe -m pip install -v Pillow"
      shell: pwsh

    - name: Build pillow-avif-plugin
      run: |
        cmd /c "winbuild\build\build_env.cmd && $env:pythonLocation\python.exe -m pip install -v ."
      shell: pwsh

    # failing with PyPy3
    - name: Enable heap verification
      if: "!contains(matrix.python-version, 'pypy')"
      run: "& 'C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x86\\gflags.exe' /p /enable $env:pythonLocation\\python.exe"

    - name: Test pillow-avif-plugin
      run: |
        path %GITHUB_WORKSPACE%\\winbuild\\build\\bin;%PATH%
        python.exe -m pytest -v -W always --cov pillow_avif --cov tests --cov-report term --cov-report xml tests
      shell: cmd

    - name: Prepare to upload errors
      if: failure()
      run: |
        mkdir -p tests/errors
      shell: pwsh

    - name: Upload errors
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: errors
        path: tests/errors

    - name: After success
      run: |
        coverage xml
      shell: pwsh

    - name: Build wheel
      id: wheel
      run: |
        cmd /c "winbuild\build\build_env.cmd && $env:pythonLocation\python.exe -m pip wheel -v ."
      shell: pwsh

    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: "*.whl"

  success:
    needs: [windows]
    runs-on: ubuntu-latest
    name: Build Successful
    steps:
      - name: Success
        run: echo Build Successful

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [windows]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
